[default]
address = "0.0.0.0"
port = 8080

[default.databases.postgres]
url = "postgres://postgres:password@postgres:5432/volleyapp"

[dev]
address = "0.0.0.0"
port = 8080

[dev.databases.postgres]
url = "postgres://postgres:password@localhost:5432/volleyapp" 